GET http://localhost:8000/users/ HTTP/1.1

###

POST http://localhost:8000/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "ahmed",
    "role": "doctor",
    "password": "123"
}

# GET	/doctor/profile/	Retrieve your own doctor profile
# PUT	/doctor/profile/	Update all fields (contact, bio, specialty)
# PATCH	/doctor/profile/	Partially update fields
GET http://localhost:8000/doctor/profile HTTP/1.1



###

# GET http://localhost:8000/user-orders/ HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxOTgzODEyLCJpYXQiOjE3NjE5ODM1MTIsImp0aSI6ImVmZjRhN2I4MDQwYTRkMDM5MmExYTJmZGE4NzFkNTQwIiwidXNlcl9pZCI6IjIifQ.8e9S9pC0QDxiwZpFm5Ol9cu5NnShd1rBPWH0omUPYMQ

# ###

# POST http://localhost:8000/api/token/refresh/ HTTP/1.1
# Content-Type: application/json

# {
#     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MjA3MDQxNywiaWF0IjoxNzYxOTg0MDE3LCJqdGkiOiIzMmNlZWU2MzAwNjU0YjAxOTM4MGU0NzE3ZGM4YzJlNyIsInVzZXJfaWQiOiIyIn0.l3Bq8AKyRb9NE4uKtTN2tQw-YhHRcLNjuWQfQRr-uhQ"
# }
