# list all users (AllowAny)
GET http://localhost:8000/users/ HTTP/1.1

### Register user

POST http://localhost:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "patientTest",
    "role": "patient",
    "password": "123456"
}
### Register doctor user

POST http://localhost:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "doctor1",
    "role": "doctor",
    "password": "123456"
}

### Patient Login
POST http://localhost:8000/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "doctor1",
    "password": "123456"
}
### Doctor Login
POST http://localhost:8000/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "123456"
}

###
# Get doctor (auth)
GET http://localhost:8000/api/doctor/dashboard/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg


### Retrieve your own doctor profile
GET	http://localhost:8000/api/doctor/profile/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg

### Update all fields (contact, bio, specialty)
PUT http://localhost:8000/api/doctor/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg

{
    "contact": "01124619944", 
    "bio": "Good Doc 2", 
    # "specialty": "<pk>",
    "user": {
        "username": "ezz",
        "password": "011012" 
    }
}


### Partially update fields
PATCH http://localhost:8000/api/doctor/profile/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg

{
    "contact": "01124619944", 
    "bio": "Good Doc" 
}


# availability ----------------

### create
POST http://localhost:8000/api/doctor/availabilities/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg
Content-Type: application/json

{
    "start_time": "08:00:00",
    "end_time": "10:00:00"
}


### retrieve one
GET http://localhost:8000/api/doctor/availabilities/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg

### update
PATCH http://localhost:8000/api/doctor/availabilities/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg
Content-Type: application/json

{
    "end_time": "11:00:00"
}

### delete
DELETE http://localhost:8000/api/doctor/availabilities/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg


### list all appointments
GET http://localhost:8000/api/patient/appointments/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY4MjU1LCJpYXQiOjE3NjI5Njc5NTUsImp0aSI6ImZkYmNlZjAwZjFlYjQ3ZTk4ODFmZmJkNDA4MTZhNjYwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiZG9jdG9yIn0.iW2ZS2RsXWH0FlVuwENZhRxF8Mr_0xSHv3jSYEnylVg
### create an appointments
POST http://localhost:8000/api/patient/appointments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyODg3NjU0LCJpYXQiOjE3NjI4ODczNTQsImp0aSI6ImU0YWEyNjdmMTQ5NzQ1NGU4NWQ2YWYxZGRkYTVjZmFkIiwidXNlcl9pZCI6IjExIiwicm9sZSI6InBhdGllbnQifQ.oSLyjG0jbgxLHIykdGoNxB2O5yju_URvAKJO7LGnZko
Content-Type: application/json

{
  "doctor": 1,
  "start_date_time": "2025-11-12T10:00:00Z",
  "end_date_time": "2025-11-12T10:30:00Z"
}
