# Generated by Django 5.2.8 on 2025-11-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='slot_duration',
            field=models.IntegerField(default=30, help_text='Duration of each slot in minutes (e.g., 15, 30, 60)'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
