# Generated by Django 5.2.8 on 2025-11-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
